### ISSUE TITLE
Hanging sign above switch makes multiple switches

### ISSUE THREAD

**Issue by caligari87** [caligari87/ObAddon#14]
Reported via Discord:

> **wildweasel:** i'm unsure what can be done about this but i would like to report an oblige issue. if a hanging sign is generated above a switch like this one, the switch effectively becomes 5 switches that all do the same thing. thankfully the action was "door open once", if it was something like "lower floor [x] units" it would have been funny

![image](https://user-images.githubusercontent.com/6425795/54075063-a9363200-4257-11e9-9a4e-32a9674cece6.png)

**Comment by Armaetus** [comment]
I remember seeing this for AGES in vanilla OBLIGE when there was a difference in lighting/ceiling height intersecting a switch light. Perhaps it's time we squash this bug once and for all, despite it not interfering with gameplay, it's just strange and makes the active switches look strange next to a linedef that has the other switch texture.

**Comment by GTD-Carthage** [comment]
This has to do with any form of geometry that happens to exist above the switch and can happen on two cases: 1) if the ceiling has a sink and this switch is right around where the sink border renders, 2) the above scenario

The first scenario could be fixable by simply... disabling ceiling sinks from appearing on areas containing a switch. The second solution I need some more thinking about - mostly because I believe point prefabs are are rendered on marked spots before walls are even erected, so the those points technically don't have any information yet so to whether there is an overhanging wall type over them...

**Comment by GTD-Carthage** [comment]
This issue might still be possible but as of right now, there is now code that attempts to stop protruding walls from interfering with importants such as switches and key pedestals.
