### ISSUE TITLE
Shuffler not using all tracks in MAPINFO

### ISSUE THREAD

**Issue by Armaetus** [caligari87/ObAddon#17]
I noticed while looking in multiple MAPINFO lumps with the "Shuffle Music" under ZDoom Special Addons is that I am seeing some tracks being used 2 or even 3 times and some not even being used at all in the music WAD I have loaded with the generated map set, even if it's an episode's worth of maps.

Not even the BEX shuffler had these issues.

**Comment by GTD-Carthage** [comment]
This should be fixable... it's just that the shuffler code runs for each map, thus a chance for duplicate entries lol

**Comment by GTD-Carthage** [comment]
This should be fixed for Doom 2, but Doom 1 is another case entirely since the ZDS Addons code still doesn't even count the maps for Doom 2 VS Ultdoom properly... I'll be closing this issue for now though and it might be preferable to open a new one specifically for Doom 1, as it involves something more than just the music shuffler...
