### ISSUE TITLE
Closed windows and doors aren't the same on both side of a wall

### ISSUE THREAD

**Issue by Demiosis** [caligari87/ObAddon#18]
![Screenshot_Doom_20190310_153914](https://user-images.githubusercontent.com/5500931/54090534-8a18cc80-434b-11e9-92f2-5d7d30d866aa.png)
![Screenshot_Doom_20190310_153918](https://user-images.githubusercontent.com/5500931/54090535-8ab16300-434b-11e9-9a80-fed59c97c1ce.png)

My suggestion for this kind of issue is to have a second branch for the window prefabs that would generate EXCLUSIVELY closed doors and windows . This would mean edition and transferring all the closed windows/doors from the walls fabs to this new branch but this would end up making the level just a tad bit better tbh.

**Comment by Armaetus** [comment]
I've seen this on the urban doors/windows and those windows that have the small view from the top, which looks a bit weird when near an actual open area and for the former, pretty strange when the wall on the adjacent side is 32 or less units from the prefab.

I am guessing some placement code could be used for these minor issues?

**Comment by GTD-Carthage** [comment]
This was formerly an impossible task for me to figure out but after successfully adding the new flat wall checks, I can also do the same for doors and windows now by requiring fake doors and windows to have a solid void behind them to render. The fix should be fairly trivial...

**Comment by GTD-Carthage** [comment]
There is now a check to make this less blatant. There may still be some very rare cases, but those 'very rare' cases should be far, far, far less obvious... the current check simply makes it so that a solid space behind the edge is 'assumed' if the space behind doesn't belong to any room, or belongs to a room but are of different heights. Hopefully the new check works, so I'm closing the issue for now!

**Comment by Demiosis** [comment]
![Screenshot_Doom_20190311_035056](https://user-images.githubusercontent.com/5500931/54108002-288b4900-43b1-11e9-9887-4afd2c2da894.png)

Worked Well until I saw it affected parks! ^^'

**Comment by Armaetus** [comment]
I'm pretty sure those are supposed to be inside only prefabs, right?

**Comment by Demiosis** [comment]
These are not inside only fabs and regarding the issue:

honestly parks in urban looks like bombeb zones/ wastelands so the fact the fabs can be either buried halfway in the ground or high up does make it pretty cool.
but its really the light under the the garage door and the un-matching texture that make it look wrong ^^''.

**Comment by GTD-Carthage** [comment]
I've set them to spawn outdoors too because otherwise, the street rooms look ridiculously barren not having doors or shutters to hint to occupancy...

That said, parks have had this stupid problem for a while lol

It's far more difficult to figure out what's going on here because I can't easily capture the height information about the different steps naturalistic parks make so for the time being, I set the floors of the doors and shutters to just use the _WALL texture of the room.

It's not exactly a fix, but let me know if you guys think negates the issue a bit more but just in case, it's preferable to open a new issue on the tracker (maybe walls not having proper floor heights in park rooms)
