### ISSUE TITLE
SLIGE theme

### ISSUE THREAD

**Issue by Epictyphlosion** [caligari87/ObAddon#20]
Basically, this theme would generate levels like the old level generator SLIGE did. This would mean that you could relive those days when you found SLIGE maps all over the /idgames archive without having to download SLIGE itself!

This would also mean that SLIGE-style maps could be generated with options not found in SLIGE, like level size, individual monster spawn rates, item spawn rates, etc.. Plus, SLIGE doesn't have an interface, while OBLIGE does, making it much easier to use!

**Comment by GTD-Carthage** [comment]
I feel as though this might really be better as an enhancement to SLIGE itself rather than Oblige as it is a sort of making a regression to build SLIGE-like maps... my personal recommendation though if you really want to get a SLIGE experience from ObAddon right now, turn Linear Mode on, make both Decor and Wall fabs really low under Prefab Control, and make sure Big Rooms = NONE and see what ObAddon might come up with. :)

**Comment by Armaetus** [comment]
Having Few/Rare/None on most settings should give you the SLIGE experience.
