### ISSUE TITLE
Lamp posts sillyness

### ISSUE THREAD

**Issue by Demiosis** [caligari87/ObAddon#22]
Them lamp posts still spawn on roads... Speaking about roads fabs spawning, I never EVER saw a vehicle spawn on the roads sadly.. =/ and finally shouldn't the small hell cracks able to spawn in streets like the flesh spikes?

![Screenshot_Doom_20190318_165226](https://user-images.githubusercontent.com/5500931/54575762-c2fc1580-49cb-11e9-9b1c-2696afbc09e6.png)

**Comment by GTD-Carthage** [comment]
This is an issue with the road ID'ing itself - it's not that the light posts are in the wrong spot, it's the road sink itself. :P I've been trying to fix this for a while so it might stick around a bit longer...

Additionally, it turns out the cars are still too big in size from LUA to spawn on the road chunk itself, which is why I'm looking for a completely different solution regarding spawning fabs on the road in general. (which hopefully I can get to when I figure out how to get positions and spots on the roads themselves to spawn fabs over in the first place)

**Comment by Armaetus** [comment]
We now have proper "Road traffic" (IE cars & stuff) and settings what prefabs can spawn on roads so I'll consider this issue closed.
