### ISSUE TITLE
TNT maps don't randomize map names

### ISSUE THREAD

**Issue by Krigeris** [caligari87/ObAddon#69]
Doom 2 maps randomize the names just fine but tnt maps (maybe plut havent checked) just give the default names that tnt maps have.

**Comment by GTD-Carthage** [comment]
No idea why this would happen but there are two methods map names are changed - through a MAPINFO lump if ZDoom Special Addons are enabled or through a DEHACKED lump (default way Oblige preserves custom map names)

Try using ZDoom Special Addons if it helps because maybe the DEHACKED patch isn't being read in your sourceport.
