### ISSUE TITLE
Script error: attempt to index local 'src_area' (a nil value)

### ISSUE THREAD

**Issue by ryanhaney97** [caligari87/ObAddon#78]
It looks like a good portion of the time when generating with the latest build (pulled from master), src_area in cave.lua is nil/null. Not too sure about how this code works, but I could at least pinpoint that. Can attach the generator settings I'm using too if that would be useful, though maybe knowing where the problem is happening is enough.

**Comment by GTD-Carthage** [comment]
The newest cutting edge build should resolve this. Try again with the new build and if it still doesn't work, post your LOG here right after an error happens. This issue was because the new vista type can't find a floor chunk to borrow a height from when facing naturalistic parks or caves (but neither rooms support any vista type)
