### ISSUE TITLE
Invisible pillar with graphical glitch associated

### ISSUE THREAD

**Issue by mridlen** [caligari87/ObAddon#81]
![Screenshot_Doom_20200621_134227](https://user-images.githubusercontent.com/5098180/85232552-4376a680-b3c5-11ea-8d4f-90aa12c8f37e.png)

**Comment by Armaetus** [comment]
That looks like it might be a node builder issue? Did you make maps on some of the latter three sizes (Colossal, Gargantuan, Transcendent)? Perhaps @GTD-Carthage can give some information?

**Comment by mridlen** [comment]
It was Microscopic I believe.

**Comment by GTD-Carthage** [comment]
This doesn't look like a CSG or node builder issue but the fab seemingly has missing side textures entirely causing the sort of infinite floor hack as above - if there is a log that can be provided in the future when this issue is encountered again, we'll definitely take a look - I will be closing this issue for now, however, I haven't seen this issue on my own play (but I'm playing entirely on Doom 2 settings).
